baseURL = "https://ayuch.dev/"
languageCode = "en-us"
title = "Ayush Chauhan"
theme = "nightfall"

[params]
user = "bakayu"
hostname = "ayuch.dev"
description = "portfolio and blog"
openLinksInNewTab = true
footerHtml = 'Â© 2025 Ayush Chauhan'
displayDateFormat = "Jan 2, 2006"

[params.author]
name = "Ayush Chauhan"
avatar = "/images/pfp.gif"
avatarSize = "size-xl"
email = "mail@ayuch.dev"
avatarFirst = false

# Social links
[[params.social]]
key = 0
name = "github"
url = "https://github.com/bakayu"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "linkedin"
url = "https://linkedin.com/in/ayuch"
target = "_blank"
aria = "LinkedIn Profile"

[[params.social]]
key = 1
name = "resume"
url = "/files/resume.pdf"
target = "_blank"
aria = "resume"


[[params.social]]
key = 3
name = "email"
url = "mailto:mail@ayuch.dev"
aria = "Email Address"

[[params.social]]
key = 4
name = "twitter"
url = "https://twitter.com/baku_ayu"
target = "_blank"
aria = "Twitter Profile"

[[params.social]]
key = 5
name = "blog"
url = "/blog"
# target = "_blank"
aria = "blog"


# Date formats
displayDateFormat = "Jan 2, 2006"

# Open external links in new tab
openLinksInNewTab = true

# Main menu
[menu]
[[menu.header]]
name = "blog"
weight = 2
url = "/blog"

[[menu.header]]
name = "about"
weight = 1
url = "/about"

# [[menu.header]]
# name = "projects"
# weight = 2
# url = "/projects"

[[menu.header]]
name = "contact"
weight = 0
url = "/contact"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# [markup.highlight]
# noClasses = false
# lineNos = false
# lineNumbersInTable = false
# tabWidth = 4

[pagination]
pagerSize = 10
